### PR TITLE
CT-3943: Upgrade cppcheck and install flawfinder from pip

### PR DESCRIPTION
**Pull request by jdonelle**
I tried getting flawfinder from pip, but I was unable to add the path to the PATH env var. From what I found online adding `PATH=$PATH:filepath` would work, but it didn't in my case. If any of you guys have an ideas pls lmk. On the bright side, flawfinder is up to date and cppcheck is version 2.7! to test use branch in CTF, I'll need to delete that branch once merged

### CODE REVIEW

**Comment by naubryGV** [comment]
Did you try this @jdonelle ?
https://dwheeler.com/flawfinder/#downloading

**Comment by jdonelle** [comment]
@naubryGV @cardinotGV I think this PR should be good for testing! I've added the python env too @cardinotGV

**Review by naubryGV — APPROVED** [review]
Looks good to me!
@cardinotGV There's just this warning in the output, but I don't think it matters as we don't keep any data between runs, right?
image

**Review by cardinotGV — APPROVED** [review]
yep, all good. Thanks James

**Pull request merged**
